name: Deploy Function App - Az-demo1

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.13'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Export requirements for Azure remote build
        run: |
          uv lock
          uv export --format requirements.txt --no-hashes --output-file requirements.txt

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F12A802F7E974BA2A4AEAFD2401CFE75 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_61BA37E5E87E4B6F8CEFD049EF9618A2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_98BD6C656EDA43199D580D69D43608EF }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'Az-demo1'
          package: '.'
          sku: flexconsumption
          remote-build: true
          respect-funcignore: true
